/**/fork_serial:
  ros__parameters:
    use_sim_time: $(var use_sim_time)
    port: /dev/ttyACM0
    baudrate: 9600
    data_bits: 8
    flow_control: none
    parity: none
    stop_bits: 1.0
    lower_limit: 0.0
    upper_limit: 0.2
    lower_ir_value: 0.1
    upper_ir_value: 0.3
    convergence_threshold: 0.01
    execution_loop_frequency: 10.0
    low_pass_filter_coeff: 0.10
    joint_name: robot_fork_carriage_joint
    command_topic: joint_commands/fork
    joint_states_topic: joint_states
